import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "HelloWorld Framework 4",
  description: "Generated by HelloWorld Framework 4",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
