import type { Metadata } from "next";
import "./globals.scss";
import Navbar from "@/components/navbar/Navbar";
import NavbarProvider from "@/store/NavbarProvider";
import ContextWrapper from "./ContextWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NavbarProvider>
      <ContextWrapper>
        <body>
          <header>
            <Navbar/>{children}
          </header>
        </body>
      </ContextWrapper>
    </NavbarProvider>
  );
}
